In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing

In [2]:
#Feature selection done automatically by ANN

In [3]:
(train_x,train_y),(test_x,test_y)=boston_housing.load_data()

In [4]:
print("Train shape : ",train_x.shape)
print("Test shape : ",test_x.shape)
print("Actual Train output : ",train_y.shape)
print("Actual Test output : ",test_y.shape)

Train shape :  (404, 13)
Test shape :  (102, 13)
Actual Train output :  (404,)
Actual Test output :  (102,)


In [5]:
train_y

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

In [6]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [7]:
train_y[0]

15.2

In [8]:
train_x=preprocessing.normalize(train_x)

In [9]:
test_x=preprocessing.normalize(test_x)

In [14]:
train_x[0].shape

(13,)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *

In [15]:
def housePricePredictionModel():
    model=Sequential() #output of 1 layer will to provided to other
    model.add(Dense(128,activation='relu',input_shape=(train_x[0].shape)))
    model.add(Dense(64,activation='relu'))#No need to put explicit connections between dense layer 1 and 2
    model.add(Dense(32,activation='relu'))
    model.add(Dense(1))#No activation function required here because output
    model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
    return model

In [17]:
import numpy as np
k=4
num_val_samples = len(train_x)
num_epochs=100
all_scores=[]

In [20]:
model=housePricePredictionModel()
history=model.fit(x=train_x, y=train_y, epochs=num_epochs, batch_size=1, verbose=1, validation_data=(test_x,test_y))

Epoch 1/100
404/404 [==============================] - 2s 3ms/step - loss: 120.7466 - mae: 7.7391 - val_loss: 65.2214 - val_mae: 6.0356
Epoch 2/100
404/404 [==============================] - 1s 2ms/step - loss: 67.5973 - mae: 5.6985 - val_loss: 61.0586 - val_mae: 6.0186
Epoch 3/100
404/404 [==============================] - 1s 2ms/step - loss: 63.3176 - mae: 5.4427 - val_loss: 56.9813 - val_mae: 5.4858
Epoch 4/100
404/404 [==============================] - 1s 2ms/step - loss: 60.1170 - mae: 5.4261 - val_loss: 54.9908 - val_mae: 5.4036
Epoch 5/100
404/404 [==============================] - 1s 2ms/step - loss: 57.5318 - mae: 5.2216 - val_loss: 57.0136 - val_mae: 5.7868
Epoch 6/100
404/404 [==============================] - 1s 2ms/step - loss: 55.5646 - mae: 5.1161 - val_loss: 55.8981 - val_mae: 5.2717
Epoch 7/100
404/404 [==============================] - 1s 2ms/step - loss: 54.0744 - mae: 4.9652 - val_loss: 57.1929 - val_mae: 5.8742
Epoch 8/100
404/404 [==============================] -

404/404 [==============================] - 1s 2ms/step - loss: 18.6145 - mae: 3.0504 - val_loss: 32.6742 - val_mae: 4.1159
Epoch 62/100
404/404 [==============================] - 1s 2ms/step - loss: 19.6256 - mae: 3.2387 - val_loss: 30.6685 - val_mae: 3.8194
Epoch 63/100
404/404 [==============================] - 1s 2ms/step - loss: 18.3891 - mae: 3.0699 - val_loss: 26.3731 - val_mae: 3.5354
Epoch 64/100
404/404 [==============================] - 1s 2ms/step - loss: 17.7809 - mae: 3.0066 - val_loss: 31.9254 - val_mae: 4.0341
Epoch 65/100
404/404 [==============================] - 1s 2ms/step - loss: 19.0574 - mae: 3.1550 - val_loss: 29.2519 - val_mae: 3.6547
Epoch 66/100
404/404 [==============================] - 1s 2ms/step - loss: 18.1142 - mae: 3.0339 - val_loss: 33.0238 - val_mae: 4.1800
Epoch 67/100
404/404 [==============================] - 1s 2ms/step - loss: 18.6011 - mae: 3.0514 - val_loss: 27.0489 - val_mae: 3.5547
Epoch 68/100
404/404 [==============================] - 1s 2m

In [21]:
loss, mae = model.evaluate(test_x, test_y, verbose=0)

print(f'Test Mean Absolute Error: {mae:.2f}')

Test Mean Absolute Error: 4.07


In [22]:
test_x[0]

array([0.02675675, 0.        , 0.02677953, 0.        , 0.0010046 ,
       0.00951931, 0.14795322, 0.0027145 , 0.03550877, 0.98536841,
       0.02988655, 0.04031725, 0.04298041])

In [23]:
test_y[0]

7.2

In [24]:
inp=[[0.02675675, 0.        , 0.02677953, 0.        , 0.0010046 ,
       0.00951931, 0.14795322, 0.0027145 , 0.03550877, 0.98536841,
       0.02988655, 0.04031725, 0.04298041]]

In [25]:
model.predict(inp)

1/1 [==============================] - 0s 137ms/step


array([[8.649243]], dtype=float32)