In [126]:
import pandas as pd

In [127]:
df=pd.read_csv('HousingData.csv')

In [128]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO   
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3  \
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [129]:
df.isna().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [130]:
df.dropna(inplace=True)

In [106]:
y=df['MEDV']

In [132]:
from sklearn import preprocessing
xtrain=preprocessing.normalize(xtrain)
xtest=preprocessing.normalize(xtest)

In [133]:
x=df.drop(columns=['MEDV'],axis=1)

In [134]:
x.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO   
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3  \
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
5  0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622    3  222     18.7   

        B  LSTAT  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
5  394.12   5.21

In [135]:
x=x.to_numpy()

In [136]:
y=y.to_numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [137]:
x[:5]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00],
       [2.9850e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.4300e+00, 5.8700e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9412e+02, 5.2100e+00]])

In [138]:
x[0].shape

(13,)

In [139]:
from sklearn.model_selection import train_test_split

In [140]:
xtrain,xtest,ytraim,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [141]:
xtrain.shape

(275, 13)

In [142]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [143]:
ann =models.Sequential([
layers.Dense(128,activation='relu',input_dim=13),
layers.Dense(64,activation='relu'),
layers.Dense(32,activation='relu'),
layers.Dense(1)
]
)

In [144]:
ann.compile(optimizer='rmsprop',
           loss='mse',
           metrics=['mae'])

In [145]:
ann.fit(xtrain,ytraim,epochs=100)

Epoch 1/100
9/9 [==============================] - 1s 4ms/step - loss: 502.8671 - mae: 14.3771
Epoch 2/100
9/9 [==============================] - 0s 4ms/step - loss: 90.9867 - mae: 7.3273
Epoch 3/100
9/9 [==============================] - 0s 2ms/step - loss: 124.5772 - mae: 9.4435
Epoch 4/100
9/9 [==============================] - 0s 4ms/step - loss: 137.8819 - mae: 9.1702
Epoch 5/100
9/9 [==============================] - 0s 4ms/step - loss: 76.0371 - mae: 6.5400
Epoch 6/100
9/9 [==============================] - 0s 4ms/step - loss: 181.5922 - mae: 10.9808
Epoch 7/100
9/9 [==============================] - 0s 4ms/step - loss: 67.5627 - mae: 6.4163
Epoch 8/100
9/9 [==============================] - 0s 2ms/step - loss: 80.9275 - mae: 7.1343
Epoch 9/100
9/9 [==============================] - 0s 4ms/step - loss: 144.9557 - mae: 9.4035
Epoch 10/100
9/9 [==============================] - 0s 2ms/step - loss: 91.3633 - mae: 7.3271
Epoch 11/100
9/9 [==============================] - 0s 4ms/ste

9/9 [==============================] - 0s 2ms/step - loss: 28.0196 - mae: 3.7687
Epoch 89/100
9/9 [==============================] - 0s 4ms/step - loss: 33.6314 - mae: 4.1744
Epoch 90/100
9/9 [==============================] - 0s 4ms/step - loss: 33.8434 - mae: 4.2248
Epoch 91/100
9/9 [==============================] - 0s 4ms/step - loss: 24.7807 - mae: 3.5140
Epoch 92/100
9/9 [==============================] - 0s 4ms/step - loss: 30.8514 - mae: 4.0599
Epoch 93/100
9/9 [==============================] - 0s 4ms/step - loss: 34.1263 - mae: 4.3566
Epoch 94/100
9/9 [==============================] - 0s 4ms/step - loss: 28.7464 - mae: 3.9063
Epoch 95/100
9/9 [==============================] - 0s 4ms/step - loss: 28.8226 - mae: 3.8593
Epoch 96/100
9/9 [==============================] - 0s 2ms/step - loss: 33.0453 - mae: 4.2438
Epoch 97/100
9/9 [==============================] - 0s 2ms/step - loss: 23.5365 - mae: 3.4675
Epoch 98/100
9/9 [==============================] - 0s 2ms/step - loss: 3

In [146]:
ann.evaluate(xtest,ytest)

4/4 [==============================] - 0s 0s/step - loss: 45.1451 - mae: 4.9048


[45.14506530761719, 4.904785633087158]

In [147]:
ypred=ann.predict(xtest)

4/4 [==============================] - 0s 5ms/step


In [150]:
ytest[5:11]

array([33.8, 19.7, 24.8, 32. , 14. , 21.7])

In [151]:
ypred[5:11]

array([[30.211191],
       [23.897003],
       [28.859758],
       [29.768116],
       [16.902658],
       [23.439768]], dtype=float32)